import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import ComicCard, { CardType } from 'dh-marvel/components/cards/comic-card';
import Pagination from '@mui/material/Pagination';
import Stack from '@mui/material/Stack';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import { styled } from '@mui/material/styles';
import { useState, useEffect, ChangeEvent } from 'react';

type Props = {
    data: CardType[],
    totalPages: number
}

const Item = styled(Paper)(({ theme }) => ({
    backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
    ...theme.typography.body2,
    padding: theme.spacing(1),
    margin: theme.spacing(1)
}));

const Index: NextPage<Props> = ({ data, totalPages }: Props) => {
    const [page , setPage] = useState<number>(1)

    useEffect( () => {
        async function getData () {
            const result = await fetch("api/comics/?page="+ page)
            console.log(result);
        }
        getData();
    }, [page])

    const hadleChange = (event: ChangeEvent<unknown> , value : number)  =>{
        setPage(value)
    }
    return (
        <>
            <Head>
                <title>Home Marvel Comics</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <BodySingle title={"Cómics"}>
                <Box sx={{ flexGrow: 1, display: "flex", alignItems: "center", flexDirection: "column" }}>
                    <Grid container spacing={3} sx={{ marginBottom: 5 }}>
                        {data.map(d => {
                            return (
                                    <Item key={d.id}>
                                        <ComicCard data={d} />
                                    </Item>)
                        })}
                    </Grid>
                    <Stack spacing={2} sx={{ marginBottom: 5 }}>
                        <Pagination
                            count={totalPages}
                            color="primary"
                            onChange={hadleChange}
                            />
                    </Stack>
                </Box>
            </BodySingle>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const res = await getComics(0, 12);
    const totalPages = Math.ceil(res.data.total / 12);
    return {
        props: { data: res.data.results, totalPages }
    }
}
export default Index
