import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import FaqsComponent from "../components/faqs/faqsComponent"
import { faqsData, FaqsType } from 'dh-marvel/components/faqs/faqsData';

interface Props {
    data: FaqsType[]
}
const Faqs: NextPage<Props> = ({ data }: Props) => {
    return (
        <>
            <Head>
                <title>Preguntas Frecuentes</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <BodySingle title={"Preguntas Frecuentes"}>
                {data.map(faq => <FaqsComponent key={faq.id} faq={faq} />)}
            </BodySingle>
        </>
    )
}
export const getStaticProps: GetStaticProps = async () => {
    const data = faqsData;
    return {
        props: { data: data }
    }
}
export default Faqs;
