import type {NextPage} from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";

const Faqs: NextPage = () => {
    
    return (
        <>
            <Head>
                <title>Faqs</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <BodySingle title={"Preguntas Frecuentes"}>
                asdasdasdasdas
            </BodySingle>
        </>
    )
}

export default Faqs;
